### ISSUE TITLE
Can't init project

### ISSUE THREAD

**Issue by KingErroneous55** [gameclosure/devkit#118]
I am using git bash on Windows XP. I get the following error when initing a project:

ERROR Error: ENOSYS, function not implemented 'c:\development\devkit\hello-world\sdk'
    at Object.fs.symlinkSync (fs.js:730:18)
    at initProject (c:\dev\devkit\src\init\index.js:80:5)
    at Object.exports.init (c:\dev\devkit\src\init\index.js:57:2)
    at SuperGroup.main (c:\dev\devkit\src\basil.js:299:22)
    at SuperGroup.<anonymous> (c:\dev\devkit\node_modules\ff\lib\ff.js:282:14)
    at SuperGroup.<anonymous> (c:\dev\devkit\node_modules\ff\lib\ff.js:389:23)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
basil exited with an error. The logs are in /tmpbasil.log.
Contact our support team (support@gameclosure.com) with these logs for assistance.

**Comment by jwilm** [comment]
This issue was related to devkit-v1. As we update for devkit2, such issues are being closed as "likely to be fixed in devkit2". If the issue persists after updating, please reopen it. Thank you!
