### ISSUE TITLE
The installation was successful, but an error occurred when running example

### ISSUE THREAD

**Issue by realdog** [gameclosure/devkit#161]
When I installed everything, I ran 
$ Basil init hello-world 
$ Cd. / Hello-world 
$ Basil serve 
$ Basil serve-p 8080 
Currently there are no errors 
but, "With the project loaded, launch the simulator for it by clicking the Simulate button located in the upper-left corner.". . . . 
Some error has occurred

============================================================
                   {{ Game Closure SDK }}                   
                       release-0.1.45
                 Like fireworks in a shed.
------------------------------------------------------------
      [java]    [warn]  java version "1.7.0_45"
      [java]   Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
      [java]    [warn]  Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
     [basil]    Serving from project directory, attempting to automatically register..
    starting server, session url is <>
    INFO .env.node.csp Listening csp@:9225
    INFO .env.node.tcp Listening tcp@:9226
     [basil]    Server launched at http://localhost:8080/
     [basil]    Your local IP is [ '192.168.1.104' ]
     [native]    native inspector exited with code 8
     [jvmtools]    Connected to daemon on localhost:51398
     [jsio]    Compiling Source code.
     [jsio]    jsio_compile "import GUI,preprocessors.import,preprocessors.cls" --jsioPath  "sdk/jsio" --noIE "true" --environment "browser" --path "    [\".\",\"sdk/jsio\",\"sdk/gc/api/\",\"sdk/\",\"sdk/timestep/\",\"src/serve/plugins/simulate/stati c\"]" --includeJsio "true" --appendImport "false" --debug "4" --cwd "/sdk/devkit"
     Error loading module:
 	[[ import squill.Window ]]
 	requested by: src/serve/plugins/simulate/static/GUI.js 
 	current directory: /sdk/devkit 
 	Error: requested import (squill.Window) not found
	looked in:
		sdk/jsio/squill/Window.js
		./squill/Window.js
		sdk/gc/api/squill/Window.js
		../squill/Window.js
		sdk/timestep/squill/Window.js
		src/serve/plugins/simulate/static/squill/Window.js
	Import Stack:		 
 	Error: requested import (squill.Window) not found
	looked in:
		sdk/jsio/squill/Window.js
		./squill/Window.js
		sdk/gc/api/squill/Window.js
		../squill/Window.js
		sdk/timestep/squill/Window.js
		src/serve/plugins/simulate/static/squill/Window.js
	Import Stack:		
        at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:535:11)
        at Function.importer [as __importer] (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
        at run (sdk/jsio/preprocessors/compiler.js:246:7)
        at $$preprocessors_compiler.exports (sdk/jsio/preprocessors/compiler.js:91:4)
        at applyPreprocessors (/sdk/devkit/lib/js.io/packages/jsio.js:584:6)
        at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:570:5)
        at importer (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
        at /sdk/devkit/lib/js.io/packages/jsio.js:80:21
        at Function.$$preprocessors_compiler.exports.compile     (sdk/jsio/preprocessors/compiler.js:242:2)
        at Object.$$jsio_compile_compiler.exports.run     (/sdk/devkit/lib/js.io/compilers/jsio_compile/compiler.js:234:11)
WARN preprocessors.compiler could not compile import from  src/serve/plugins/simulate/static/GUI.js: import squill.Window
    Error loading module:
 	[[ import squill.Widget ]]
 	requested by: src/serve/plugins/simulate/static/GUI.js 
 	current directory: /sdk/devkit 
 	Error: requested import (squill.Widget) not found
	looked in:
		sdk/jsio/squill/Widget.js
		./squill/Widget.js
		sdk/gc/api/squill/Widget.js
		../squill/Widget.js
		sdk/timestep/squill/Widget.js
		src/serve/plugins/simulate/static/squill/Widget.js
	Import Stack:		 
 	Error: requested import (squill.Widget) not found
	looked in:
		sdk/jsio/squill/Widget.js
		./squill/Widget.js
		sdk/gc/api/squill/Widget.js
		../squill/Widget.js
		sdk/timestep/squill/Widget.js
		src/serve/plugins/simulate/static/squill/Widget.js
	Import Stack:		
        at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:535:11)
        at Function.importer [as __importer] (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
        at run (sdk/jsio/preprocessors/compiler.js:246:7)
        at $$preprocessors_compiler.exports (sdk/jsio/preprocessors/compiler.js:91:4)
        at applyPreprocessors (/sdk/devkit/lib/js.io/packages/jsio.js:584:6)
        at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:570:5)
        at importer (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
        at /sdk/devkit/lib/js.io/packages/jsio.js:80:21
        at Function.$$preprocessors_compiler.exports.compile   (sdk/jsio/preprocessors/compiler.js:242:2)
        at Object.$$jsio_compile_compiler.exports.run (/sdk/devkit/lib/js.io/compilers/jsio_compile/compiler.js:234:11)
WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/GUI.js: import squill.Widget
    Error loading module:
 	[[ import squill.Delegate ]]
 	requested by: src/serve/plugins/simulate/static/GUI.js 
 	current directory: /sdk/devkit 
 	Error: requested import (squill.Delegate) not found
	looked in:
		sdk/jsio/squill/Delegate.js
		./squill/Delegate.js
		sdk/gc/api/squill/Delegate.js
		../squill/Delegate.js
		sdk/timestep/squill/Delegate.js
		src/serve/plugins/simulate/static/squill/Delegate.js
	Import Stack:		 
 	Error: requested import (squill.Delegate) not found
	looked in:
		sdk/jsio/squill/Delegate.js
		./squill/Delegate.js
		sdk/gc/api/squill/Delegate.js
		../squill/Delegate.js
		sdk/timestep/squill/Delegate.js
		src/serve/plugins/simulate/static/squill/Delegate.js
	Import Stack:		
        at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:535:11)
        at Function.importer [as __importer] (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
        at run (sdk/jsio/preprocessors/compiler.js:246:7)
        at $$preprocessors_compiler.exports (sdk/jsio/preprocessors/compiler.js:91:4)
        at applyPreprocessors (/sdk/devkit/lib/js.io/packages/jsio.js:584:6)
        at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:570:5)
        at importer (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
        at /sdk/devkit/lib/js.io/packages/jsio.js:80:21
        at Function.$$preprocessors_compiler.exports.compile (sdk/jsio/preprocessors/compiler.js:242:2)
        at Object.$$jsio_compile_compiler.exports.run (/sdk/devkit/lib/js.io/compilers/jsio_compile/compiler.js:234:11)
    WARN preprocessors.compiler could not compile import from   src/serve/plugins/simulate/static/GUI.js: import squill.Delegate
    WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/util/Inspector.js: import squill.Widget as Widget
    WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/util/Simulator.js: import squill.Widget
    WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/util/Simulator.js: import squill.Window
    Error loading module:
        [[ import squill.Drag ]]
         requested by: src/serve/plugins/simulate/static/util/Simulator.js 
         current directory: /sdk/devkit 
         Error: requested import (squill.Drag) not found
	 in:
               sdk/jsio/squill/Drag.js
               ./squill/Drag.js
               sdk/gc/api/squill/Drag.js
               ../squill/Drag.js
               sdk/timestep/squill/Drag.js
               src/serve/plugins/simulate/static/squill/Drag.js
        Import Stack:		 
 	      Error: requested import (squill.Drag) not found
	      looked in:
               sdk/jsio/squill/Drag.js
		./squill/Drag.js
		sdk/gc/api/squill/Drag.js
		../squill/Drag.js
		sdk/timestep/squill/Drag.js
		src/serve/plugins/simulate/static/squill/Drag.js
        Import Stack:		
          at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:535:11)
          at Function.importer [as __importer] (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
          at run (sdk/jsio/preprocessors/compiler.js:246:7)
          at $$preprocessors_compiler.exports (sdk/jsio/preprocessors/compiler.js:91:4)
           at applyPreprocessors (/sdk/devkit/lib/js.io/packages/jsio.js:584:6)
          at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:570:5)
          at Function.importer [as __importer] (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
          at run (sdk/jsio/preprocessors/compiler.js:246:7)
          at $$preprocessors_compiler.exports (sdk/jsio/preprocessors/compiler.js:91:4)
          at applyPreprocessors (/sdk/devkit/lib/js.io/packages/jsio.js:584:6)
          WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/util/Simulator.js: import squill.Drag
          WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/GUI.js: 'import ..addons.' + name + '.index'
          Error loading module:
          [[ import squill.cssLoad ]]
          requested by: src/serve/plugins/simulate/static/GUI.js 
          current directory: /sdk/devkit 
          Error: requested import (squill.cssLoad) not found
          looked in:
          sdk/jsio/squill/cssLoad.js
          ./squill/cssLoad.js
          sdk/gc/api/squill/cssLoad.js
          ../squill/cssLoad.js
          sdk/timestep/squill/cssLoad.js
          src/serve/plugins/simulate/static/squill/cssLoad.js
          Import Stack:
          Error: requested import (squill.cssLoad) not found
          looked in:
          sdk/jsio/squill/cssLoad.js
          ./squill/cssLoad.js
          sdk/gc/api/squill/cssLoad.js
          ../squill/cssLoad.js
          sdk/timestep/squill/cssLoad.js
          src/serve/plugins/simulate/static/squill/cssLoad.js
          Import Stack:		
          at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:535:11)
          at Function.importer [as __importer] (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
          at run (sdk/jsio/preprocessors/compiler.js:246:7)
          at $$preprocessors_compiler.exports (sdk/jsio/preprocessors/compiler.js:91:4)
          at applyPreprocessors (/sdk/devkit/lib/js.io/packages/jsio.js:584:6)
          at loadModule (/sdk/devkit/lib/js.io/packages/jsio.js:570:5)
          at importer (/sdk/devkit/lib/js.io/packages/jsio.js:687:18)
          at /sdk/devkit/lib/js.io/packages/jsio.js:80:21
          at Function.$$preprocessors_compiler.exports.compile           (sdk/jsio/preprocessors/compiler.js:242:2)
          at Object.$$jsio_compile_compiler.exports.run (/sdk/devkit/lib/js.io/compilers/jsio_compile/compiler.js:234:11)
          WARN preprocessors.compiler could not compile import from src/serve/plugins/simulate/static/GUI.js: import squill.cssLoad
          WARN preprocessors.compiler could not compile import from sdk/jsio/preprocessors/import.js: ' + p2 + '

**Comment by KRamdath** [comment]
I'm still getting the above error in the current build.

**Comment by jwilm** [comment]
@KRamdath what part of it? Half of that log doesn't exist in the current version.

**Comment by KRamdath** [comment]
Immediately after "devkit serve", when loading "loaclhost:9200", the following error is thrown loading the squill.cssLoad module:

>Error loading module:
>     [[ import squill.cssLoad ]]
>     requested by: ./apps.js 
>     current directory: http://localhost:9200/ 
>   Error: Could not import `squill.cssLoad`
>  	looked in:
>  		../../../node_modules\squill/cssLoad.js
>  		../../../node_modules\squill/cssLoad/index.js
>  	Import Stack:
>  		1: ".apps" apps.js:662
>      at ENV_browser.loadModule (http://localhost:9200/compile/apps.js:700:17)
>      at _require (http://localhost:9200/compile/apps.js:856:34)
>      at Object.jsio (http://localhost:9200/compile/apps.js:88:27)
>      at Object.$$_apps (http://localhost:9200/apps.html/apps.js:17:1)
>      at execModuleDef (http://localhost:9200/compile/apps.js:768:10)
>      at _require (http://localhost:9200/compile/apps.js:907:11)
>      at http://localhost:9200/compile/apps.js:88:27
>      at http://localhost:9200/compile/apps.js:1058:517529
