### ISSUE TITLE
Error: Cannot find module 'jsio'

### ISSUE THREAD

**Issue by sunshine17** [gameclosure/devkit#18]
this error happened when i run ./install script on centos 5.5:
module.js:340
    throw err;
          ^
Error: Cannot find module '/var/linzy/wsp/devkit/sdk/jsio/jsio'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.exports.loadJsio (/var/linzy/wsp/devkit/src/common.js:45:13)
    at Object.<anonymous> (/var/linzy/wsp/devkit/src/common.js:50:9)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Successfully installed. Type "basil" to begin.

**Comment by krk** [comment]
After second init, jsio will work on Windows.

```
devkit init abc
devkit init def
```

**Comment by collingreen** [comment]
@krk It will work on the second, but not the first?

**Comment by krk** [comment]
Yes it will. btw I have switched to linux.
