### ISSUE TITLE
Unhandled Error when executing devkit on OS x

### ISSUE THREAD

**Issue by SClinton** [gameclosure/devkit#191]
Any clue why this is showing up?

Possibly unhandled Error: [object Object]
    at ReductionPromiseArray.PromiseArray$_reject (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise_array.js:161:63)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:671:17)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:988:14)
    at Promise$_rejectPromises [as _rejectPromises] (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise.js:981:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:419:13)

**Comment by collingreen** [comment]
Hi @SClinton - I still haven't run into this myself - what version of devkit are you using?

**Comment by collingreen** [comment]
@SClinton are you still running into this? If so, can you supply any more information to help me reproduce it?

**Comment by collingreen** [comment]
Closing this for now. If you have more info, please re-open!
