### ISSUE TITLE
Error: Could not import `.globals`

### ISSUE THREAD

**Issue by synthecypher** [gameclosure/devkit#197]
Followed instructions on DevKit docs, met all requirements.

```
C:\Users\Josh\Projects
λ devkit

Error loading module:
     [[ ./globals ]]
     requested by: ./<initial file>
     current directory: C:\Users\Josh\Projects
   Error: Could not import `.globals`
        looked in:
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals.js
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals/index.js
        Import Stack:

      at loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:693:17)
      at ENV_node.loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:462:18)
      at _require (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:856:34)
      at C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:88:27
      at Object.<anonymous> (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src\devkit.js:30:1)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)

C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:879
          throw err;
                ^
Error: Could not import `.globals`
        looked in:
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals.js
                C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src/globals/index.js
        Import Stack:

    at loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:693:17)
    at ENV_node.loadModule (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:462:18)
    at _require (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:856:34)
    at C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\node_modules\jsio\packages\jsio.js:88:27
    at Object.<anonymous> (C:\Users\Josh\AppData\Roaming\npm\node_modules\devkit\src\devkit.js:30:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by synthecypher** [comment]
Wrong repo.
