### ISSUE TITLE
Builds don't work on windows

### ISSUE THREAD

**Issue by jwilm** [gameclosure/devkit#205]
Even when `ndk-build` is in the user's path, it seems to not be found in the process spawned by `build.js` in _native-android_.

**Comment by jgamao** [comment]
I am using ubuntu in building the release .

**Comment by jwilm** [comment]
My mistake, let me take another look at that.

**Comment by jgamao** [comment]
It's ok.. 


Thank you for answering my question.

**Comment by jwilm** [comment]
If you run `ndk-build -v` from a terminal do you get anything? It looks like you don't have the android-ndk installed, or you have it installed and it's not on your path.

**Comment by jgamao** [comment]
Yes I think I don't have it.. Yesterday I downloaded ndk and sdk.. I think my mistake was my path in my .bashrc.

**Comment by jgamao** [comment]
This is what I do in my .bashrc

export PATH=$PATH:~/Download/android-ndk-r10d/prebuilt/linux-x86_64/bin
export PATH=$PATH:~/Download/android-ndk-r10d
export PATH=$PATH:~/Download/android-sdk-linux/tools
export PATH=$PATH:~/Download/android-sdk-linux/platforms

**Comment by jwilm** [comment]
I think you should just need `export PATH=$PATH:~/Download/android-ndk-r10d`. Although, I might change it to `export PATH=$PATH:$HOME/Download/android-ndk-r10d`. You should also double check that `ndk-build` is in that folder. If you haven't created a new shell, your bashrc won't have run again. Also try running `source ~/.bashrc`.

**Comment by jgamao** [comment]
The ndk-build is in the folder.

I have already command source ~/.bashrc in the terminal and there's no error..

How about the sdk..Do I need it in my path?

**Comment by jgamao** [comment]
It is still having an error.. 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by jwilm** [comment]
Can you provide the full log?

**Comment by jgamao** [comment]
ok..

**Comment by jgamao** [comment]
[build]    starting build at Thu Feb 12 2015 09:59:23 GMT+0800 (PHT)
         [apps]    /home/joselito/wt-calamityrun/manifest.json
       [module]    browser-mobile
       [module]    /home/joselito/wt-calamityrun/modules/devkit-core/src/build/browser
       [module]    browser-desktop
       [module]    /home/joselito/wt-calamityrun/modules/devkit-core/src/build/browser
       [module]    native-ios
       [module]    /home/joselito/wt-calamityrun/modules/devkit-core/src/build/native/native-ios
       [module]    native-android
       [module]    /home/joselito/wt-calamityrun/modules/devkit-core/src/build/native/native-android

        [build]    Prebuild phase completed for Calamity Run
        [build]    	build for: native-android 		scheme: release

 --- start config ---
                     appPath: /home/joselito/wt-calamityrun
                       debug: false
                      scheme: release
                      target: native-android
                  schemePath: build/release
                  outputPath: /home/joselito/wt-calamityrun/build/release/native-android
                jsioPath:
                    jsioPath: /home/joselito/wt-calamityrun/build/release/native-android
                  sdkVersion: 2.0.0
                   isTestApp: undefined
                 isSimulated: undefined
               simulator:
                    deviceId: undefined
                  deviceType: undefined
                        port: undefined
                        port: undefined
                          ip: 192.168.1.138
                  serverName: production
          outputResourcePath: /home/joselito/wt-calamityrun/build/release/native-android/assets/resources
                      studio: studio.wetalkdirect.com
                     version: 0.2.0
                    compress: true
                       appID: a36dd79473ea4dac97b1a48ed892466d
              localBuildPath: build/release/native-android
                    bundleID: com.wetalkdirect.studio.calamity_run
                 packageName: com.wetalkdirect.studio.calamity_run
                   isAndroid: true
                      repack: false
               enableLogging: false
               resourcesOnly: false
 --- end config ---
 [build-native]    Writing resources for a36dd79473ea4dac97b1a48ed892466d with target native-android
 [jsio-compile]    compiling import devkit.native.launchClient
 [jsio-compile]    jsio_compile "import devkit.native.launchClient" --cwd "/home/joselito/wt-calamityrun" --environment "native" --path "[\"/home/joselito/wt-calamityrun/modules/devkit-core/node_modules/jsio/packages\",\".\",\"lib\",\"modules/devkit-core/modules/timestep/src\"]" --includeJsio "true" --appendImport "false" --debug "4" --pathCache "{\"devkit\":\"modules/devkit-core/src/clientapi\",\"ff\":\"modules/devkit-core/src/clientapi/api/ff\",\"menus\":\"modules/devkit-menus/src\",\"squill\":\"modules/devkit-core/modules/squill\"}" --compressorCachePath "build/release/.js-cache-native-android" --defines "{\"BUILD_TARGET\":\"native-android\",\"BUILD_ENV\":\"native\",\"DEBUG\":false}" --printOutput  --gcManifest "/home/joselito/wt-calamityrun/manifest.json" --gcDebug "false" --preprocessors "[\"cls\",\"logger\"]" --compressSources "true" --compressResult "true"
      [spriter]    spriter --no-clean --cache-file "spritercache-e24708880153df5f4acc618325b62668" --scale "1" --dir "/home/joselito/wt-calamityrun/resources/" --output "/home/joselito/wt-calamityrun/build/release/native-android/assets/resources/spritesheets" --target "native-android" --binaries "undefined" --is-simulator "undefined" --spriter-png-fallback "false"
LOG .__imports__ Including native runtime.
wrote spritesheetSizeMap.json to /home/joselito/wt-calamityrun/build/release/native-android/assets/resources/spritesheets/spritesheetSizeMap.json
     [jvmtools]    connected to localhost:36585
[build-browser]    Finished packaging resources
 [jsio-compile]    compressing JS...
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-world-map-20.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-world-map-21.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-world-map-22.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-inventory0.png
 [build-native]    Writing resource: spritesheets/resources-images-pregameScreen-inventory1.png
 [build-native]    Writing resource: spritesheets/resources-images-characterScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-characterScreen1.png
 [build-native]    Writing resource: spritesheets/resources-images-countryScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-countryScreen1.png
 [build-native]    Writing resource: spritesheets/resources-images-countryScreen2.png
 [build-native]    Writing resource: spritesheets/resources-images-statsScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-itemdrops_uncomplete0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets0.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets1.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets2.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets3.png
 [build-native]    Writing resource: spritesheets/resources-images-shopScreen-shop-assets4.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen1.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen2.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen3.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen4.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen5.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen6.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-backup0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-item_dock0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-items0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-naruto0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-stickman0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-archive-naruto0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-archive-stickman0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-base0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity0.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity1.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity2.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity3.png
 [build-native]    Writing resource: spritesheets/resources-images-gameScreen-sprite-calamity4.png
 [build-native]    Writing resource: spritesheets/resources-images-topScoreScreen0.png
 [build-native]    Writing resource: spritesheets/resources-images-ui0.png
 [build-native]    Writing resource: spritesheets/resources-images-titleScreen0.png
 [build-native]    Writing resource: resources/images/shopScreen.zip
 [build-native]    Writing resource: resources/audio/music/gameScreen.mp3
 [build-native]    Writing resource: resources/audio/music/titleScreen.mp3
 [build-native]    Writing resource: resources/audio/sounds/jump.mp3
 [build-native]    writing files to /home/joselito/wt-calamityrun/build/release/native-android/assets/resources
wrote spritesheets/resources-images-pregameScreen0.png
wrote spritesheets/resources-images-pregameScreen-world-map-20.png
wrote spritesheets/resources-images-pregameScreen-world-map-21.png
wrote spritesheets/resources-images-pregameScreen-world-map-22.png
wrote spritesheets/resources-images-pregameScreen-inventory0.png
wrote spritesheets/resources-images-pregameScreen-inventory1.png
wrote spritesheets/resources-images-characterScreen0.png
wrote spritesheets/resources-images-characterScreen1.png
wrote spritesheets/resources-images-countryScreen0.png
wrote spritesheets/resources-images-countryScreen1.png
wrote spritesheets/resources-images-countryScreen2.png
wrote spritesheets/resources-images-statsScreen0.png
wrote spritesheets/resources-images-shopScreen0.png
wrote spritesheets/resources-images-shopScreen-itemdrops_uncomplete0.png
wrote spritesheets/resources-images-shopScreen-shop-assets0.png
wrote spritesheets/resources-images-shopScreen-shop-assets1.png
wrote spritesheets/resources-images-shopScreen-shop-assets2.png
wrote spritesheets/resources-images-shopScreen-shop-assets3.png
wrote spritesheets/resources-images-shopScreen-shop-assets4.png
wrote spritesheets/resources-images-gameScreen0.png
wrote spritesheets/resources-images-gameScreen1.png
wrote spritesheets/resources-images-gameScreen2.png
wrote spritesheets/resources-images-gameScreen3.png
wrote spritesheets/resources-images-gameScreen4.png
wrote spritesheets/resources-images-gameScreen5.png
wrote spritesheets/resources-images-gameScreen6.png
wrote spritesheets/resources-images-gameScreen-backup0.png
wrote spritesheets/resources-images-gameScreen-item_dock0.png
wrote spritesheets/resources-images-gameScreen-items0.png
wrote spritesheets/resources-images-gameScreen-sprite-naruto0.png
wrote spritesheets/resources-images-gameScreen-sprite-stickman0.png
wrote spritesheets/resources-images-gameScreen-sprite-archive-naruto0.png
wrote spritesheets/resources-images-gameScreen-sprite-archive-stickman0.png
wrote spritesheets/resources-images-gameScreen-sprite-base0.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity0.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity1.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity2.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity3.png
wrote spritesheets/resources-images-gameScreen-sprite-calamity4.png
wrote spritesheets/resources-images-topScoreScreen0.png
wrote spritesheets/resources-images-ui0.png
wrote spritesheets/resources-images-titleScreen0.png
wrote resources/images/shopScreen.zip
wrote resources/audio/music/gameScreen.mp3
wrote resources/audio/music/titleScreen.mp3
wrote resources/audio/sounds/jump.mp3
wrote manifest.json
wrote native.js
    [ndk-build]    ndk-build -j 8 RELEASE=1
      [android]    android create project --target android-15 --name calamity_run --path /home/joselito/wt-calamityrun/build/release/native-android --activity calamity_runActivity --package com.wetalkdirect.studio.calamity_run

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

**Comment by jwilm** [comment]
OH. This cannot find the SDK. I think it failed at `android create project`, so I assume `android` is not on your path.

**Comment by jgamao** [comment]
Yes.. So I need to put a path for the android in my .bashrc?

**Comment by jwilm** [comment]
It seems that way, yes.

**Comment by jgamao** [comment]
It's not still working.. How to put a path for androi?

**Comment by jwilm** [comment]
Do you have android installed?

**Comment by jgamao** [comment]
I'm not sure if I have android installed... How can I know if there's android installed?
